In [2]:
import pandas as pd

#original dataset variable
orders_original = pd.read_csv('Files/fastdeliver_orders.csv')

#dublicated dataset variable
orders_dublicate = orders_original

#shows the first 5 rows of out dataset
orders_dublicate.head()

,order_id,customer_name,pickup_zone,delivery_zone,rider_id,order_date,pickup_time,delivery_time,order_value,delivery_fee,status,payment_method,rider_rating
0,FD-00029,Fatima Bello,Surulere,Ikeja,RDR-023,2026-07-28,13:31,14:45,6137.01,844.62,DELIVERED,card,2.7
1,FD-00257,Ifeanyi Nwachukwu,Yaba,Ojodu,RDR-030,2026-07-28,12:26,13:53,13387.28,508.26,Delivered,transfer,2.7
2,FD-00277,Segun Balogun,Victoria Island,Lekki,RDR-025,2026-07-01,09:21,09:52,13881.6,1183.82,delivered,NaN,3.5
3,FD-00301,Obinna Okonkwo,Surulere,Lekki,RDR-009,2026-07-16,14:31,15:19,"₦10,627.49",1165.94,delivered,transfer,2.8
4,FD-00423,Chidi Okeke,Ojodu,Ikeja,RDR-029,2026-07-23,13:19,NaN,13464.73,327.81,Failed,card,4.4

In [3]:
#identify the number of dublicates in our dataset
orders_dublicate.duplicated().sum()

np.int64(40)

In [4]:
#drop the duplicated rows in our dataset
orders_dublicate = orders_dublicate.drop_duplicates()

In [ ]:
#check if the dublicates have been dropped
orders_dublicate.duplicated().sum()

In [27]:
orders_dublicate.isna().sum()

order_id          0
customer_name     0
pickup_zone       0
delivery_zone     0
rider_id          0
order_date        0
pickup_time       0
delivery_time     0
order_value       0
delivery_fee      0
status            0
payment_method    0
rider_rating      0
total_revenue     0
dtype: int64

In [ ]:
#fill the null values in the rider_rating column with the median value of the column
orders_dublicate['rider_rating'] = orders_dublicate['rider_rating'].fillna(  
    orders_dublicate['rider_rating'].median()
 )

In [ ]:
#fill payment_method column null values with 'unknown'
orders_dublicate['payment_method'] = orders_dublicate['payment_method'].fillna('unknown')

In [ ]:
## removal of the ₦ sign and commas from the order_value column and convert it to float
orders_dublicate["order_value"] = (
    orders_dublicate["order_value"]
    .astype(str)
    .str.replace("₦", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
    .astype(float)
)

In [ ]:
#fill the null values in the order_value column with the median value of the column
orders_dublicate['order_value'] = orders_dublicate['order_value'].fillna(
    orders_dublicate['order_value'].median())

In [ ]:
#removal of the null values in the pickup_time column by converting it to datetime and filling the null values with the median date value of the column
orders_dublicate['pickup_time'] = pd.to_datetime(orders_dublicate['pickup_time'], errors='coerce', format='%H:%M')

In [ ]:
#fill the null values in the pickup_time column with the median value of the column
orders_dublicate["pickup_time"] = orders_dublicate["pickup_time"].fillna(
    orders_dublicate["pickup_time"].median()
)

In [ ]:
# Convert the pickup_time column to HH:MM format using strftime
orders_dublicate['pickup_time'] = orders_dublicate['pickup_time'].dt.strftime('%H:%M')

In [ ]:
#removal of the null values in the delivery_time column by converting it to datetime
orders_dublicate['delivery_time'] = pd.to_datetime(orders_dublicate['delivery_time'], errors='coerce', format='%H:%M')

In [ ]:
#fill the null values in the delivery_time column with the median value of the column
orders_dublicate["delivery_time"] = orders_dublicate["delivery_time"].fillna(
    orders_dublicate["delivery_time"].median()
)

In [ ]:
# Convert the delivery_time column to HH:MM format using strftime
orders_dublicate['delivery_time'] = orders_dublicate['delivery_time'].dt.strftime('%H:%M')

In [ ]:
# Convert the order_date column to datetime format
orders_dublicate['order_date'] = pd.to_datetime(orders_dublicate['order_date'], errors='coerce', format='%Y-%m-%d')

In [ ]:
# Convert the status column to lowercase and remove leading/trailing whitespace
orders_dublicate['status'] = orders_dublicate['status'].str.lower().str.strip()

In [17]:
# Convert text columns to strings datatype
orders_dublicate = orders_dublicate.astype({
    'order_id': 'string',
    'customer_name': 'string',
    'pickup_zone': 'string',
    'delivery_zone': 'string',
    'rider_id': 'string',
    'status': 'string',
    'payment_method': 'string',
})

#### Analytical Pipeline

In [23]:
#Add a Total Revenue column to the dataset by adding the order_value column and the delivery_fee column

orders_dublicate['total_revenue'] = orders_dublicate['order_value'] + orders_dublicate['delivery_fee']

In [24]:
#which zone generates the most revenue?

orders_dublicate.groupby('delivery_zone').agg(
    Total_Revenue=('total_revenue', 'sum')
).sort_values(by='Total_Revenue', ascending=False)

                 Total_Revenue
delivery_zone
Surulere             739123.17
Ojodu                726072.53
Lekki                677214.05
Ikeja                672473.57
Victoria Island      619358.32
Yaba                 547317.60

In [33]:
#Which rider has the highest failure rate?

orders_dublicate.groupby('rider_id').agg({
    'rider_rating': 'sum',
}).sort_values(by='rider_rating', ascending=True)

          rider_rating
rider_id
RDR-024           25.8
RDR-017           31.9
RDR-004           36.8
RDR-002           39.9
RDR-013           43.9
RDR-018           44.7
RDR-019           45.3
RDR-028           47.3
RDR-005           48.6
RDR-015           49.0
RDR-027           49.0
RDR-025           49.6
RDR-006           50.6
RDR-016           53.4
RDR-009           55.6
RDR-022           57.2
RDR-030           57.6
RDR-023           60.3
RDR-012           62.1
RDR-021           62.7
RDR-014           65.3
RDR-020           65.4
RDR-007           65.5
RDR-008           67.4
RDR-029           71.5
RDR-001           73.4
RDR-026           74.3
RDR-011           77.1
RDR-003           78.1
RDR-010           86.6

In [21]:
#What is the average delivery time?
pd.to_datetime(orders_dublicate['delivery_time'], format='%H:%M').mean().strftime('%H:%M')

'15:13'

In [22]:
orders_dublicate.head()

,order_id,customer_name,pickup_zone,delivery_zone,rider_id,order_date,pickup_time,delivery_time,order_value,delivery_fee,status,payment_method,rider_rating
0,FD-00029,Fatima Bello,Surulere,Ikeja,RDR-023,2026-07-28,13:31,14:45,6137.01,844.62,delivered,card,2.7
1,FD-00257,Ifeanyi Nwachukwu,Yaba,Ojodu,RDR-030,2026-07-28,12:26,13:53,13387.28,508.26,delivered,transfer,2.7
2,FD-00277,Segun Balogun,Victoria Island,Lekki,RDR-025,2026-07-01,09:21,09:52,13881.60,1183.82,delivered,unknown,3.5
3,FD-00301,Obinna Okonkwo,Surulere,Lekki,RDR-009,2026-07-16,14:31,15:19,10627.49,1165.94,delivered,transfer,2.8
4,FD-00423,Chidi Okeke,Ojodu,Ikeja,RDR-029,2026-07-23,13:19,15:13,13464.73,327.81,failed,card,4.4